language: java

notifications:
  email: true

jdk:
  - oraclejdk8

install:
  - mvn install -DskipTests -Dmaven.javadoc.skip=true

script:
  - echo "mvn package assembly:single"
  - mvn package assembly:single

before_deploy:
  # Set up git user name and tag this
  - git config --local user.name "JustWe"
  - git config --local user.email "lfk_dsk@hotmail.com"
  - git tag "Just-EL $(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - mv target/*.jar
  - mv target/surefire-reports/*

deploy:
  provider: releases
  api_key: 9924dc5c077801f239a7a3801e055e03ea714aba
  file: target/just-el-2.2.1-SNAPSHOT-jar-with-dependencies.jar
  skip_cleanup: true
  on:
    tags: true